[package]
name = "json_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = "0.14"
sonic-rs = "0.3"

[profile.release]
lto = true
codegen-units = 1
